### ISSUE TITLE
Unable to do triangulation for a valid data (I think)?

### ISSUE THREAD

**Issue by qingluwww** [NMO13/earclipper#4]
Hi, really great to find this useful repo! It works for me in most common cases, but I have some issues when it comes to less common cases.
I have this example. My raw data is example 6, I thought it was due to some inaccuracy on my side, so I simplified it to example 5, but still it throws an error. I think it's a valid polygon, and seems to be in the same plane. It's from a rotated I-beam, so the shape looks just like an I-beam extrude.

`           

           // example 5
            var points = new List<Vector3m>()
           {
                new Vector3m(7197, -131, -6003),
                new Vector3m(7197, 131, -6003),
                new Vector3m(7103, 131, -6115),
                new Vector3m(7103, 145, -6115),
                new Vector3m(7296, 145, -5884),
                new Vector3m(7296, 131, -5884),
                new Vector3m(7202, 131, -5996),
                new Vector3m(7202, -131, -5996),
                new Vector3m(7296, -131, -5884),
                new Vector3m(7296, -145, -5884),
                new Vector3m(7103, -145, -6115),
                new Vector3m(7103, -131, -6115)
            };
            var earClipping = new EarClipping();
            earClipping.SetPoints(points);
            earClipping.Triangulate();
            var res = earClipping.Result;
            PrintTriangles(res);

            // example 6
            points = new List<Vector3m>()
            {
                new Vector3m(7197.2792162972564, -131, -6003.2649404376552),
                new Vector3m(7197.2792162972564, 131, -6003.2649404376552),
                new Vector3m(7103.9723400461444, 131, -6115.2331919389362),
                new Vector3m(7103.9723400461444, 145, -6115.2331919389362),
                new Vector3m(7296.0276599455174, 145, -5884.7668080597978),
                new Vector3m(7296.0276599455174, 131, -5884.7668080597978),
                new Vector3m(7202.7207836944053, 131, -5996.7350595610787),
                new Vector3m(7202.7207836944053, -131, -5996.7350595610787),
                new Vector3m(7296.0276599455174, -131, -5884.7668080597978),
                new Vector3m(7296.0276599455174, -145, -5884.7668080597978),
                new Vector3m(7103.9723400461444, -145, -6115.2331919389362),
                new Vector3m(7103.9723400461444, -131, -6115.2331919389362)
            };
            earClipping = new EarClipping();
            earClipping.SetPoints(points);
            earClipping.Triangulate();
            res = earClipping.Result;
            PrintTriangles(res);

`

**Comment by NMO13** [comment]
Hi!

I'll have a look at it soon!

**Comment by NMO13** [comment]
@qingluwww I just investigated your polygon. I wanted to draw it in Blender but stopped already after the 4th vertex. Your polygon seems to be self intersecting. Have a look at the screenshot below.

![image](https://github.com/NMO13/earclipper/assets/3988444/bd28d189-fe41-4da0-a057-5c11fd9c09ec)

Can you fix your polygon and try again pls?

**Comment by NMO13** [comment]
I was wrong, it is of course not self-intersecting but the points are not perfectly coplanar as described by @Lokarian.

@Lokarian added a feature to map non-coplanar points onto a plane. See https://github.com/NMO13/earclipper/pull/8

**Comment by qingluwww** [comment]
Thank you very much!
