### ISSUE TITLE
Publish as Nuget Package?

### ISSUE THREAD

**Issue by SamuelReithmeir** [NMO13/earclipper#6]
Do you consider publishing this as a Nuget Package yourself.
I needed this Library in another Project and wanted it as a package.
I was so free and packaged it as a .net 7.0 Nuget package under https://www.nuget.org/packages/EarClipper 
I made clear that it is just a repackage and credited this repository.
Would you consider a restructure of the Project such that it can be published directly from this repo?
I could make a PR/help with the restructure

**Comment by NMO13** [comment]
Hi @Lokarian! Thank you for your effort!
Of course we can do that. I have no time for restructuring but if you make a PR I will merge it.

**Comment by NMO13** [comment]
Is this issue resolved now?

**Comment by SamuelReithmeir** [comment]
no, while this repo now contains a publishable package, the only nuget package on nuget.org is still the one i published, 
so evertime you would update this repo, i would need to build, packgage and upload it.
If you want to i can add you as a owner on the nuget website, so you can do that yourself.
Or i could look into how to publish a package from a github action, such that new releases of this package would automatically publish a nuget package version.

**Comment by NMO13** [comment]
OK thanks for the info.
You can add me as owner if you want. I will update it.

**Comment by SamuelReithmeir** [comment]
What is your username on nuget.org?

**Comment by NMO13** [comment]
NMO13
