### ISSUE TITLE
Bug in a specific polygon with hole

### ISSUE THREAD

**Issue by zDonik1** [NMO13/earclipper#9]
I have tested the algorithm implementation with the following polygon, and it doesn't work, throwing an exception.
https://www.desmos.com/calculator/6wykwamdrx

![image](https://github.com/NMO13/earclipper/assets/25223592/28f4d97c-f2b1-4ecf-9066-6cb433f8e9ac)

**Comment by NMO13** [comment]
I'll check your PR, thanks.

**Comment by NMO13** [comment]
@zDonik1 I cannot reproduce that.

I use this setup

          // Example 6
          List<Vector3m> points = new List<Vector3m>()
          {
              new Vector3m(0, 0, 0), new Vector3m(0, 8, 0), new Vector3m(0, 8, 4), new Vector3m(0,0,4),
          };

          // specify holes in CW order
          List<List<Vector3m>> holes = new List<List<Vector3m>>();
          Vector3m[] hole2 = { new Vector3m(0, 4, 2), new Vector3m(0, 5, 3), new Vector3m(0, 7, 2), new Vector3m(0, 6, 1) };
          holes.Add(hole2.ToList());

          EarClipping earClipping = new EarClipping();
          earClipping = new EarClipping();
          earClipping.SetPoints(points, holes);
          earClipping.Triangulate();
          var res = earClipping.Result;
          PrintTriangles(res);


I doesn't throw an exception. Can you check again pls?

**Comment by zDonik1** [comment]
I get an error when the polygons are on the XY plane, and the hole should start with `(7, 2)`.

Here is what I used for testing:
```cs
            List<Vector3m> points = new List<Vector3m>()
            {
                new Vector3m(0, 0, 0),
                new Vector3m(8, 0, 0),
                new Vector3m(8, 4, 0),
                new Vector3m(0, 4, 0)
            };

            // specify holes in CW order
            List<List<Vector3m>> holes = new List<List<Vector3m>>();
            Vector3m[] hole =
            {
                new Vector3m(7, 2, 0),
                new Vector3m(6, 1, 0),
                new Vector3m(4, 2, 0),
                new Vector3m(5, 3, 0),
            };
            holes.Add(hole.ToList());

            EarClipping earClipping = new EarClipping();
            earClipping.SetPoints(points, holes);
            earClipping.Triangulate();
            var res = earClipping.Result;
            PrintTriangles(res);
```

It is a very specific instance, but I happen to have stumbled on it.
